# Generated by Django 5.1 on 2024-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribenew", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="card_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
