# Generated by Django 5.0.7 on 2024-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribenew', '0002_subscription_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='authpayuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
